# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 志云宝宝的生活记录
subtitle: 用照片和视频记录每一天
description: 生活 | 摄影 | 旅行 | 日常
author: 志云宝宝
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://israel-liu.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "studio/**"

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
prismjs:
  enable: false

# Category & Tag
default_category: 生活
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 12
pagination_dir: page

# Extensions
theme: butterfly

# Deployment
deploy:
  type: git
  repository: https://github.com/israel-Liu/israel-Liu.github.io.git
  branch: master
