#title
title: theForger
# Header
menu:
    主页 : /
    关于 : /about
    分类 : /tags
    归档 : /archives
# title
header:
    aboutHeader: Chat
    aboutInformation: Social
    aboutFriendlink: Talent

# author chat
chat: 杨滋滋的生活得有代码音乐，还有远方的人

# SubNav
subnav:
  gitHub: "https://github.com/yzzting"
  zhiHu: "https://www.zhihu.com/people/yang-zi-zi-1995"

# friendlink
friendlink:
    ahonn的博客: http://www.ahonn.me
    刘帆帆的博客: http://henbukexue.science
# read more
excerpt_link: ...continue reading

# favicon
favicon: http://7xp1k3.com1.z0.glb.clouddn.com/octocat-de-los-muertos.jpg

# Baidu Analytics
# baidu_analytics: c21994907883f37ffd80e13627dd4faa

# Google Analytics
google_analytics: UA-75314797-1

# comments
disqus: yzzting
# duoshuo: yzzting

# photo link
aboutPhoto: http://7xp1k3.com1.z0.glb.clouddn.com/156_1.jpg
tagPhoto: http://7xp1k3.com1.z0.glb.clouddn.com/83_1.jpg
archivePhoto: https://thumbnail0.baidupcs.com/thumbnail/fa12cddfa5b220e910747545a7868ab7?fid=2961169006-250528-171464972375249&time=1480406400&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-DoP43eFHkzYn86ubtWIio6jK54k%3d&expires=8h&chkbd=0&chkv=0&dp-logid=7739478664887350419&dp-callid=0&size=c10000_u10000&quality=90

# Blog main color
# Default | Mint Green | Pale Denim | Hot Pink | Dark Violet
blog-color: Pale Denim

# Blog code theme
# Default | Night | Eighties | Blue | Bright
code-theme: Default
